version: '3'
services:
  goaws:
    image: pafortin/goaws
    ports:
    - 4100:4100
    volumes:
    - ./tests/config:/conf

  integration-tests:
    build:
      context: .
      dockerfile: tests/config/Dockerfile
    image: aiorazemax_test
    volumes:
    - .:/app
    env_file:
    - tests/config/local.env
    depends_on:
    - goaws
    entrypoint: ["./tests/config/wait-for-it.sh", "goaws:4100", "--"]
    command: ["pytest", "-m", "integration"]

  unit-tests:
    build:
      context: .
      dockerfile: tests/config/Dockerfile
    image: aiorazemax_test
    volumes:
    - .:/app
    command: ["pytest", "-m", "not integration"]
